// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13GlAyO6xBH7ab3Zkmib5nUh39A6gcFs',
    appId: '1:606724867640:android:353ba17242569dae50c8cd',
    messagingSenderId: '606724867640',
    projectId: 'learnflutter-dfacf',
    storageBucket: 'learnflutter-dfacf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUevSDX49fLup7v6Wz8ZDb4CrHC-qL6fU',
    appId: '1:606724867640:ios:1de77d77a5b35de450c8cd',
    messagingSenderId: '606724867640',
    projectId: 'learnflutter-dfacf',
    storageBucket: 'learnflutter-dfacf.appspot.com',
    androidClientId: '606724867640-e7losrod9r7q3nbgv782u5fd9av1k0vq.apps.googleusercontent.com',
    iosClientId: '606724867640-jrjrq33vs2gira5dmkrd5t6ehkjba2ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.onTheWay',
  );
}
